[package]
name = "mimir-ast"
version = "0.1.0"
edition = "2021"

[dependencies]
rspirv = "0.12.0+sdk-1.3.268.0"
syn = { version = "2.0.90", features = ["full"] }
serde = {version = "1.0.217", features = ["derive"]}
serde_json = "1.0"
quote = "1.0"