[package]
name = "mimir"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.90", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0.92"
mimir-ast = { path = "../mimir-ast" }
rspirv = "0.12.0+sdk-1.3.268.0"